### ISSUE TITLE
Get all chips from chipsview

### ISSUE THREAD

**Issue by kim1059** [DoodleScheduling/android-material-chips#6]
Hey and thanks for the great library. Is there anyway to get all the current chips in the chipsview?

**Comment by AlexanderThiele** [comment]
Hi Kim, 
this is not possible at the moment but i added a getter for the next release:

```java
mChipsView.getChips()
```

**Comment by kim1059** [comment]
when do you plan to set a new release?

**Comment by myacxy** [comment]
If you do not want to wait for a new release, you can always pull any version via [jitpack.io](https://jitpack.io/#DoodleScheduling/android-material-chips) instead. 

For example, if you want to pull the specific commit that fixes this issue, then adjust your application's `build.gradle` as follows:
```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile('com.github.DoodleScheduling:android-material-chips:a4a17ea') {
        exclude module: 'appcompat-v7'
    }
}
```
In order to pull any other version, simply swap `a4a17ea` with the first 7 characters of your desired commit's hash code (see jitpack's [documentation](https://jitpack.io/docs/) for more information).
