### ISSUE TITLE
ChipsView does not get cursor focus

### ISSUE THREAD

**Issue by Natanji** [DoodleScheduling/android-material-chips#7]
I've tried adding the sample MainActivity to an existing Android project (Conversations, an XMPP client). I copied the code and layout 1-to-1, merely renaming the activity and making it extend Activity instead of AppCompatActivity (since I don't need the additional features).

In the example, I can add chips via the RecycleView without any problem whatsoever, just like in the provided sample project. I also can click into the added chips, remove them, or click twice on them such as to activate the "edit" functionality.

However, the cursor never appears when I click on the ChipsView and keyboard for text input *never* appear. Not when I click into the ChipsView when it is empty, not when chips are already present, not even when editing a Chip.

Any idea why this might be happening? You can also check out https://github.com/Natanji/Conversations (just run the ConferenceKeywordsActivity directly) if you want to see this behaviour first-hand.

**Comment by myacxy** [comment]
Hi @Natanji,
I had a look at your implementation and also have had the issue of the missing cursor. I was able to fix it by extending `ConferenceKeywordActivity` from `AppCompatActivity` instead of `Activity` as shown in our sample. You also have to make sure that your `AndroidManifest.xml` applies a `Theme` deriving from `Theme.AppCompat` to your `ConferenceKeywordActivity`.
